cloudinary:
    cloud-name: dn0akydmv
    api-key: 883779744122919
    api-secret: 2q8MUhDG4sUjtN47HZS823Zxjko
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/neotour
        username: postgres
        password: ronaldinho80
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8082